
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app-deployment
  labels:
    app: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring-app
        image: lali19/monitoring_app
        ports:
        - containerPort: 5000
